//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektNet
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Pogoda
    {
        public int Id { get; set; }
        public string Miasto { get; set; }
        public Nullable<double> Temperatura { get; set; }
        public string Wiatr { get; set; }
        public string Ciśnienie { get; set; }
        public string Wilgotność { get; set; }
    }
}
